# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thibault Godin
tagline:          'Theoretical Computer Science: automaton groups, tilings, games...'
url:              http://thibgodin.github.ioc
shorturl:         thibgodin.github.io

author:
  name:           'Thibault Godin'

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/thibgodin/thibgodin.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/docs/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
- jekyll-paginate
