---
layout: default
title: Thibault Godin
---


_godin [at] liafa.univ-paris-diderot.fr_

_Thématiques_ : **Groupe d'automates, génération aléatoire de groupes**, et de manière plus générale,  informatique théorique et mathématiques discrètes, en particulier théorie des automates, pavages, théorie des jeux.

English version [here](https://www.irif.fr/en/users/godin/index)

Doctorant en troisième année sous la direction d'[Ines Klimann](https://www.irif.univ-paris-diderot.fr/~klimann/) et [Matthieu Picantin](https://www.irif.univ-paris-diderot.fr/~picantin/), membre du projet ANR [MealyM](https://www.irif.univ-paris-diderot.fr/~klimann/MealyM/index.php?page=accueil). Un résumé succinct de mes recherches se trouve {{ :users:godin:researchstatement.pdf |ici}}.

# Thibault Godin #
IRIF 
Bâtiment Sophie Germain, 8 place Aurélie Nemours 
F-75013 Paris 
4th floor 
Office **4060**






# Articles  #
## Publiés ou acceptés ##

     -[An Analogue to Dixon's Theorem for Automaton Groups](https://hal.inria.fr/hal-01378815); **_ANALCO 2017_**.

     -[[http://arxiv.org/abs/1604.03270|Connected reversible Mealy automata of prime size cannot generate infinite Burnside groups]]** //avec/with // Ines Klimann ; **//MFCS 2016//**.

     -[[http://arxiv.org/abs/1410.4488|On Torsion-Free Semigroups Generated by Invertible Reversible Mealy Automata]]** //avec/with // Ines Klimann & Matthieu Picantin ;  **//LATA 2015//**, {{http://dblp.uni-trier.de/rec/bibtex/conf/lata/GodinKP15|bibtex}}.


=== Soumis ou en cours de rédaction ===
==== Thibault Godin ====
IRIF \\
Bâtiment Sophie Germain, 8 place Aurélie Nemours \\
F-75013 Paris \\
4th floor \\
Office **4060**


==== Articles ====
=== Publiés ou acceptés===

     * **[[https://hal.inria.fr/hal-01378815|An Analogue to Dixon's Theorem for Automaton Groups]]** ; **//ANALCO 2017//**.

     * **[[http://arxiv.org/abs/1604.03270|Connected reversible Mealy automata of prime size cannot generate infinite Burnside groups]]** //avec/with // Ines Klimann ; **//MFCS 2016//**.

     * **[[http://arxiv.org/abs/1410.4488|On Torsion-Free Semigroups Generated by Invertible Reversible Mealy Automata]]** //avec/with // Ines Klimann & Matthieu Picantin ;  **//LATA 2015//**, {{http://dblp.uni-trier.de/rec/bibtex/conf/lata/GodinKP15|bibtex}}.


=== Soumis ou en cours de rédaction ===
