---
layout: default
title: Thibault Godin
---




# Thibault Godin #
IRIF 
Bâtiment Sophie Germain, 8 place Aurélie Nemours 
F-75013 Paris 
4th floor 
Office **4060**


<div class="blurb">
	<h1>Under construction</h1>
	<p>PhD student at <em> IRIF</em> . <a href="https://www.irif.fr/~klimann/MealyM/index.php?page=accueil"> Project MealyM</a></p>
</div><!-- /.blurb -->


powered by [Jekyll](http://jekyllrb.com)

# Articles  #
## Publiés ou acceptés ##

     -[An Analogue to Dixon's Theorem for Automaton Groups](https://hal.inria.fr/hal-01378815); **_ANALCO 2017_**.

     -[[http://arxiv.org/abs/1604.03270|Connected reversible Mealy automata of prime size cannot generate infinite Burnside groups]]** //avec/with // Ines Klimann ; **//MFCS 2016//**.

     -[[http://arxiv.org/abs/1410.4488|On Torsion-Free Semigroups Generated by Invertible Reversible Mealy Automata]]** //avec/with // Ines Klimann & Matthieu Picantin ;  **//LATA 2015//**, {{http://dblp.uni-trier.de/rec/bibtex/conf/lata/GodinKP15|bibtex}}.


=== Soumis ou en cours de rédaction ===
==== Thibault Godin ====
IRIF \\
Bâtiment Sophie Germain, 8 place Aurélie Nemours \\
F-75013 Paris \\
4th floor \\
Office **4060**


==== Articles ====
=== Publiés ou acceptés===

     * **[[https://hal.inria.fr/hal-01378815|An Analogue to Dixon's Theorem for Automaton Groups]]** ; **//ANALCO 2017//**.

     * **[[http://arxiv.org/abs/1604.03270|Connected reversible Mealy automata of prime size cannot generate infinite Burnside groups]]** //avec/with // Ines Klimann ; **//MFCS 2016//**.

     * **[[http://arxiv.org/abs/1410.4488|On Torsion-Free Semigroups Generated by Invertible Reversible Mealy Automata]]** //avec/with // Ines Klimann & Matthieu Picantin ;  **//LATA 2015//**, {{http://dblp.uni-trier.de/rec/bibtex/conf/lata/GodinKP15|bibtex}}.


=== Soumis ou en cours de rédaction ===
